-- english-tracker · seed generado desde scripts/seed-data.json — NO editar a mano.
-- Fuente: Revisión detallada por clase — Ruta Inglés A1 · sección A · Cámara y edición (agosto 2026)
-- Excluidas del seguimiento:
--   · Inglés Básico A1 para Principiantes — clase 7 (71372), clip ajeno incrustado · no aplica
--   · Estrategias 2022 — clases 5 y 11 · no aplica (deprecado)
--   · Fechas, Horas y Expresiones Simples — clase 20 · no aplica (2395 deprecado, reemplazado por 13082 y 12989 — confirmado por JuanPa)

INSERT OR IGNORE INTO batches (id, name, position) VALUES ('t1', 'Tanda 1 — lista para agendar ya', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t1-01', 't1', 'Preposiciones (audio)', 'grabación', 'Clases 1, 7, 8, 9 · segmentos ''have a look at the screen'' (~6-8 min)', 'M', 'Ravee Lakhmani', 7, 'MEDIA', 'Formato: audio que señala una pantalla inexistente — Reeditar los segmentos ''have a look at the screen'' con descripciones verbales autosuficientes de las posiciones (o insertar audio-descripción), para que el andamiaje de lugar funcione en modo podcast', 'Grabación: De acuerdo, se necesita crear los guiones y pedir al profesor hacer la grabación.', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-01', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-01', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-01', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-01', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-01', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-01', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t1-02', 't1', 'Inglés para Viajes (audio)', 'reedición', 'Clase 2 [01:13–01:40] y clase 10 [04:52]', 'S', 'Carolina Boquín', 1, 'MEDIA', 'Referencias rotas (clases VR retiradas) — Recortar las menciones a las 3 clases VR inactivas (cls 2 [01:13-01:40], cls 10 [04:52]) o reactivar/regrabar ese bonus; hoy es promesa rota evaluada en examen', 'Reedición: Puedo hacer los cortes de audio y pedir a edición que rehagan el rénder del apoyo visual.', 1);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-02', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-02', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-02', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-02', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-02', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-02', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t1-03', 't1', 'Pronunciación', 'reedición', 'Clase 18 · [07:37–07:53]', 'S', 'Mariana Lafon', 0.5, 'MEDIA', 'Modelo incorrecto dictado (''catched'', ''payed'') — Reeditar el segmento final del ejercicio ([07:37]-[07:53]) que dicta las formas incorrectas ''catched'' y ''payed'' como palabras a practicar (deberían ser caught/paid o sustituirse por regulares)', 'Reedición: ¿cómo haríamos esto? Quizás podríamos ver con edición si entrenando un modelo rápido con la voz de la profe, pudiéramos corregir estas palabras mal pronunciadas, ya que probablemente contactarla para regrabar este pequeño segmento no sea tan óptimo.', 2);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-03', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-03', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-03', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-03', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-03', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t1-03', 'done', 0);

INSERT OR IGNORE INTO batches (id, name, position) VALUES ('t2', 'Tanda 2 — ruta obligatoria', 1);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-01', 't2', 'Práctica y Checkpoint de Salida A1', 'nuevo', 'Curso nuevo (~6-8 clases) — no existe', 'L', 'por asignar', 21, 'ALTA', 'Modo sin práctica medible (interacción oral y teléfono) — ''Práctica y Checkpoint de Salida A1'': ~6-8 clases — sesiones guiadas de simulador (escenarios rescatados de 2175/2395), tarea telefónica (material de 3996), checkpoint contra el banco. Requiere A07/A08 resueltos', 'Nuevo: De acuerdo.', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-01', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-01', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-01', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-01', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-01', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-01', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-02', 't2', 'Escritura', 'nuevo', '3 clases nuevas — no existe', 'M', 'Fernanda Machado', 10.5, 'ALTA', 'Can-dos sin fuente (escritura transaccional) — Formulario de registro · formulario de compra en línea · tarjeta/postal — dentro de 2256 tras su renivelación A2', 'Nuevo: No comprendo bien el objetivo aquí.', 1);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-02', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-02', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-02', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-02', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-02', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-02', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-03', 't2', 'Vocabulario y Expresiones', 'nuevo', '2-3 segmentos nuevos sobre clases existentes — no existe', 'S', 'René Lora', 4.5, 'MEDIA', 'Can-dos sin fuente (mediación es↔en) — Añadir la capa ''transmítelo en español'' sobre los letreros/menús/cuentas que 2921 ya muestra en pantalla', 'Nuevo: No entiendo muy bien cómo iría esto de "Transmítelo en español".', 2);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-03', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-03', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-03', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-03', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-03', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-03', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-04', 't2', 'Vocabulario y Expresiones', 'reedición', 'Clase 14 (segmento present continuous) y clase 17 (segmento past simple)', 'M', 'René Lora', 15, 'MEDIA', 'Nivel equivocado (A2 como objetivo) — Reencuadrar present continuous (14) y past simple (17) como exposición receptiva o mover a A2; decisión de matriz a nivel ruta, no urgente por sí sola', 'Reedición: Concuerdo en que el presente contínuo debería reubicarse, ¿regrabaríamos las partes que están en este tiempo por expresiones en presente simple?', 3);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-04', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-04', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-04', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-04', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-04', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-04', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-05', 't2', 'Escritura', 'grabación', 'Clases 17 (rutinas con adverbios) y 18 (biografía en pasado) + nivel de tareas del curso', 'M', 'Fernanda Machado', 8, 'MEDIA', 'Nivel equivocado (tareas A2 como objetivo) — Reencuadrar ambas clases a tareas A1 (rutina simple en presente; descripción de una persona en vez de biografía en pasado). Va junto con la renivelación general A2', 'Grabación: De acuerdo, se necesita crear los guiones y pedir al profesor hacer la grabación.', 4);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-05', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-05', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-05', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-05', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-05', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-05', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-06', 't2', 'Verbo To Be', 'reedición', 'Clase 10 · cierre (~últimos 20s)', 'S', 'Jhon Carvajal', 0.3, 'BAJA', 'Tarea desalineada con lo enseñado — Reeditar el cierre (últimos ~20s) para que la tarea pida escribir presentaciones con ''this is'' + saludo, no descripciones genéricas', 'Reedición: De acuerdo. Podemos grabar con voz en off y pedir a edición apoyar con motion graphics.', 5);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-06', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-06', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-06', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-06', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-06', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-06', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-07', 't2', 'Escritura', 'reedición', 'Clase 2 · segmento acrónimos (~2.5 min)', 'S', 'Fernanda Machado', 2.5, 'BAJA', 'Metalenguaje fuera de nivel — Recortar el segmento acrónimo/inicialismo y punto británico vs americano (≈2.5 min de metalenguaje fuera de A1) de la clase más larga del curso', 'Reedición: Puedo hacer estos cortes y resubir la clase.', 6);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-07', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-07', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-07', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-07', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-07', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-07', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-08', 't2', 'Inglés para el Trabajo', 'reedición', 'Clase 13 · cierre', 'S', 'Gina Pedraza', 2, 'BAJA', 'Material de examen invisible para el estudiante — Añadir al video los perfiles de los dos candidatos (hoy solo en worksheet) para que los ítems de examen tengan base en el video; duración actual anómala (1m14s)', 'Reedición: De acuerdo. Podemos grabar con voz en off y pedir a edición apoyar con motion graphics.', 7);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-08', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-08', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-08', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-08', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-08', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-08', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t2-09', 't2', 'Vocabulario y Expresiones', 'reedición', 'Clases 2, 6, 8, 10, 18 · líneas y CTAs sueltos', 'S', 'René Lora', 4, 'MEDIA', 'Nivel equivocado (A2 en CTAs y diálogos) — Micro-reediciones: quitar o sustituir las líneas A2 incidentales (''I''ve made up my mind'', comparativos en diálogo) y los CTAs que exigen past simple', NULL, 8);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-09', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-09', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-09', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-09', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-09', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t2-09', 'done', 0);

INSERT OR IGNORE INTO batches (id, name, position) VALUES ('t3', 'Tanda 3 — condicionadas y opcionales', 2);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t3-01', 't3', 'Viajes en video', 'nuevo', 'Curso nuevo opcional (~10-12 clases) — reemplaza al audio 2175', 'L', 'por asignar', 38.5, 'MEDIA', 'Refuerzo opcional (audiencia de viajes) — En video (no audio), simuladores re-escritos a A1; desvío clásico de viajes', 'Nuevo: De acuerdo.', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-01', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-01', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-01', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-01', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-01', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-01', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t3-02', 't3', 'Inglés para tu Trabajo', 'nuevo', 'Curso nuevo opcional (~8-10 clases) — evolución de 3996', 'L', 'por asignar (base: Gina Pedraza)', 31.5, 'MEDIA', 'Refuerzo opcional (audiencia laboral) — Sector English profesional; vehículo natural de IS6 ampliado; entrevista marcada como puente A1+/A2', 'Nuevo: De acuerdo.', 1);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-02', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-02', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-02', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-02', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-02', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-02', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t3-03', 't3', 'Preparación Certificación A1', 'nuevo', 'Curso corto nuevo opcional (~4-6 clases) — no existe', 'M', 'por asignar', 15, 'BAJA', 'Preparación de examen (audiencia B2B) — Qué esperar del examen, práctica por modo contra el banco, simulacro completo; da meta visible (punto de Ofelia). La más especulativa: depende del contrato', 'Nuevo: De acuerdo y lo pondría prioritario.', 2);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-03', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-03', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-03', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-03', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-03', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-03', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t3-04', 't3', 'Construcción de Oraciones', 'reedición', 'Clase 18 (63860) · clip completo', 'S', 'Vicky Peña', 0.5, 'MEDIA', 'Clip duplicado y fuera de lugar — Reemplazar el clip duplicado de cl.23 por un resumen real de módulos 1-3 (o eliminar la clase y renumerar): hoy ''repasa'' contenido que aún no se ha visto; corregir ''introductions''', 'Reedición: De acuerdo. Podemos grabar con voz en off y pedir a edición apoyar con motion graphics.', 3);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-04', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-04', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-04', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-04', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-04', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-04', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t3-05', 't3', 'Estrategias para Aprender Inglés', 'reedición', 'Clase 3 (84347) · cierre (~últimos 30s)', 'S', 'Gina Pedraza', 0.5, 'MEDIA', 'Tarea sin idioma ni plantilla — Reeditar el cierre (o añadir tarjeta/recurso) para pedir la meta en inglés con plantilla A1 (''My goal is...''), convirtiendo el único CTA capturado del curso en producción PW1/IW2 real', 'Reedición: Se puede añadir ese recurso al final con un motion graphic que invite a ello.', 4);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-05', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-05', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-05', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-05', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-05', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-05', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t3-06', 't3', 'Estrategias para Aprender Inglés', 'reedición', 'Clase 8 (IA sin pena)', 'S', 'Gina Pedraza', 3, 'BAJA', 'Nivel equivocado (clase en inglés B1+) — Si el curso se conserva como recurso fuera del camino: regrabar la clase en español o con inglés A1; sus prompts apuntan a herramientas externas.', 'Reedición: no entendí bien esta parte.', 5);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-06', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-06', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-06', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-06', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-06', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-06', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t3-07', 't3', 'Inglés para Viajes (audio)', 'reedición', 'Clases 13 y 17 (segmentos parciales)', 'S', 'Carolina Boquín', 3, 'BAJA', 'Nivel equivocado (like+ing, idioms como objetivo) — Los absorbe el rediseño de Viajes en video (A146). Si Viajes sigue en audio: recortar los segmentos de idioms/like+ing o marcarlos como ''extra''.', 'Reedición: Me parece buena idea marcarlos como un segmento ''extra''.', 6);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-07', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-07', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-07', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-07', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-07', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-07', 'done', 0);
INSERT OR IGNORE INTO tasks (id, batch_id, title, work_type, scope, effort, owner, minutes, priority, source_note, production_note, position) VALUES ('t3-08', 't3', 'Inglés para el Trabajo', 'reedición', 'Clase 12 (agendar reuniones)', 'S', 'Gina Pedraza', 2, 'BAJA', 'Nivel equivocado (in/on/at de tiempo como objetivo) — Si el curso sigue en catálogo como opcional: reencuadrar el segmento a hora simple (''at 3 o''clock'' como fórmula) sin la regla in/on/at.', 'Reedición: Si bien entiendo el objetivo de esta acción, no sé en la práctica cómo la plantearíamos desde reedición. Tal vez aplique como regrabación.', 7);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-08', 'backlog', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-08', 'planning', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-08', 'execution', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-08', 'edition', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-08', 'review', 0);
INSERT OR IGNORE INTO phase_states (task_id, phase, done) VALUES ('t3-08', 'done', 0);

